### ISSUE TITLE
Make it possible to run the tool through pytest

### ISSUE THREAD

**Issue by matveypashkovskiy** [F-Secure/pytest-rts#22]
For example coverage plugin for pytest could be invoked like:

```
pytest -x
	    --cov=tests_selector
	    --cov-report=html
	    --cov-report=term
	    --cov-fail-under=90
```

can we do the same?

**Comment by matveypashkovskiy** [comment]
Here is an example of the scenario

1. `pip install pytest-rts`
2. `pytest` - runs tests_selection_init
3. `pytest` - runs tests_selection against uncommited changes/changes in the branch
4. `pyetst --no-rts` just runs all the tests
5. `pytest --rts-flaky` can run tests related to the changes and flaky tests

An example of pytest plugin implementation: https://github.com/pytest-dev/pytest-cov/blob/f66d8399b92e4a699516d7c4b456a8f4c1b10d31/src/pytest_cov/plugin.py

@guotin, @alexey-vyskubov how does it sound?

**Comment by alexey-vyskubov** [comment]
I'd rather have a plugin which has to be explicitly enabled (with `--rts` or `--rts-flaky`) than the one which has to be explicitly disabled.

**Comment by matveypashkovskiy** [comment]
good point

**Comment by matveypashkovskiy** [comment]
done #67
