### ISSUE TITLE
Improve command-line usage

### ISSUE THREAD

**Issue by alexey-vyskubov** [F-Secure/pytest-rts#42]
Instead of having multiply entry points, we should support one executable with multiple commands (`tests_selector init` instead of `tests_selector_init`) via something like [click](https://click.palletsprojects.com/en/7.x/)

We might also want to invent shorter name for the executable (I'd hate if `git` would be instead `version_control` :D), but that's "naming things" -- one of the two most difficult problem in the computer science (funny that the tool itself is pretty much about the second, which is "cache invalidation")  😄

**Comment by matveypashkovskiy** [comment]
will it collide with pytest plugins way of integration? Here how it should be [done](https://github.com/pytest-dev/pytest-cov/blob/f66d8399b92e4a699516d7c4b456a8f4c1b10d31/setup.py#L139) (pycov example)

**Comment by matveypashkovskiy** [comment]
I think it is irrelevant now after #67, but feel free to reopen it if there is a need.
