### ISSUE TITLE
What to do with evaluation code

### ISSUE THREAD

**Issue by guotin** [F-Secure/pytest-rts#45]
Hey @alexey-vyskubov & @matveypashkovskiy 

What should we do with the existing evaluation code? I spent some time this week to fix it again (could make a PR soon) but should it be somewhere else entirely? I was just thinking that if this tool is to be transformed to a pytest-plugin then is the evaluation code ever going to be used. Does it make sense that a pytest plugin contains something like that ?

**Comment by matveypashkovskiy** [comment]
I believe that evaluation code is a part of integration testing suite so it should be in that repo but probably not in tha main source code folder but in tests. It would be nice to run it time to time in CI and see the progress or find another way to integrate it.

**Comment by matveypashkovskiy** [comment]
I think it is relosved now.
