### ISSUE TITLE
README updating

### ISSUE THREAD

**Issue by guotin** [F-Secure/pytest-rts#46]
Hey @alexey-vyskubov & @matveypashkovskiy 

What should be done with the README of this repo? Is anyone ever going to read some of those articles in the table or should they just be removed? Also the other old stuff in there might be out of place.

**Comment by matveypashkovskiy** [comment]
Let's have a separate docs folder where we will have:
* web site of the project with needed docs/links
* CONTRIBUTING.md - with rules wich will help us to configure proper versioning for the module
* overview of the state of the are (references to those articles)
