### ISSUE TITLE
If directory name contains 'pytest-rts', the tool does not work

### ISSUE THREAD

**Issue by alexey-vyskubov** [F-Secure/pytest-rts#62]
I was trying to produce an example for the problem with decorators we discussed, and put my code into `pytest-rts-try-decorators` directory. Because of the (incorrect) hardcoded condition in the `save_mapping_data()` the tool does not work at all: `"pytest-rts" in filename` is wrong.

**Comment by alexey-vyskubov** [comment]
@guotin also this will prevent using `pytest-rts` for testing itself, which we surely want to do.

**Comment by guotin** [comment]
Some of the files that start the coverage collection (in `pytest_rts/pytest/`) seem to like getting mapped as source files. If the condition is fully removed, then they as a often present in the `mapping.db`. On the other hand, If the condition is improved to ignore those files only, then the tool can't test them but the tool should work for other directories. Is that good enough?

**Comment by matveypashkovskiy** [comment]
I think this is fixed now. @guotin @alexey-vyskubov could you please confirm?
