### ISSUE TITLE
Indetermenistic database update

### ISSUE THREAD

**Issue by matveypashkovskiy** [F-Secure/pytest-rts#84]
@guotin or @alexey-vyskubov could you please describe the problem?

**Comment by guotin** [comment]
Here are the steps to reproduce the bug:

1. Run `pytest --rts`
2. Rename `mapping.db` to `old_mapping.db`
3. Run `pytest --rts` again to produce another `mapping.db`
4. Compare the database sizes of `mapping.db` and `old_mapping.db` -> they are different but they contain the same items
5. `sqldiff`-utility shows that there are many `UPDATE test_map SET ?, ? ,?` commands in the diff. 

So it seems that there is something weird going on in the collection of coverage information and writing it to database.

**Comment by matveypashkovskiy** [comment]
covered in #84

**Comment by matveypashkovskiy** [comment]
covered in #92
